"""initial schema

Revision ID: 767ce951bcf1
Revises: 
Create Date: 2026-09-11 12:57:29.376656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2



# revision identifiers, used by Alembic.
revision: str = '767ce951bcf1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('overall_suitability', sa.Float(), nullable=True),
    sa.Column('prospectivity', sa.Float(), nullable=True),
    sa.Column('geological_suitability', sa.Float(), nullable=True),
    sa.Column('drilling_risk_level', sa.String(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_index('idx_candidate_evaluations_location', 'candidate_evaluations', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_candidate_evaluations_candidate_id'), 'candidate_evaluations', ['candidate_id'], unique=True)
    op.create_index(op.f('ix_candidate_evaluations_id'), 'candidate_evaluations', ['id'], unique=False)
    op.create_table('formations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('formation_name', sa.String(), nullable=True),
    sa.Column('field_name', sa.String(), nullable=True),
    sa.Column('top_depth', sa.Float(), nullable=True),
    sa.Column('base_depth', sa.Float(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_formations_formation_name'), 'formations', ['formation_name'], unique=False)
    op.create_index(op.f('ix_formations_id'), 'formations', ['id'], unique=False)
    op.create_table('wells',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('well_id', sa.String(), nullable=False),
    sa.Column('well_name', sa.String(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('well_type', sa.String(), nullable=True),
    sa.Column('total_depth', sa.Float(), nullable=True),
    sa.Column('current_depth', sa.Float(), nullable=True),
    sa.Column('current_formation', sa.String(), nullable=True),
    sa.Column('spud_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completion_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_index('idx_wells_location', 'wells', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_wells_id'), 'wells', ['id'], unique=False)
    op.create_index(op.f('ix_wells_well_id'), 'wells', ['well_id'], unique=True)
    op.create_table('anomalies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('well_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('measured_depth', sa.Float(), nullable=True),
    sa.Column('parameter', sa.String(), nullable=True),
    sa.Column('observed_value', sa.Float(), nullable=True),
    sa.Column('expected_value', sa.String(), nullable=True),
    sa.Column('deviation', sa.Float(), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['well_id'], ['wells.well_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomalies_id'), 'anomalies', ['id'], unique=False)
    op.create_table('drilling_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('well_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('event_depth', sa.Float(), nullable=True),
    sa.Column('start_depth', sa.Float(), nullable=True),
    sa.Column('end_depth', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('root_cause', sa.String(), nullable=True),
    sa.Column('mitigation', sa.String(), nullable=True),
    sa.Column('npt_hours', sa.Float(), nullable=True),
    sa.Column('formation', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['well_id'], ['wells.well_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drilling_events_id'), 'drilling_events', ['id'], unique=False)
    op.create_table('drilling_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('well_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('measured_depth', sa.Float(), nullable=True),
    sa.Column('formation', sa.String(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['well_id'], ['wells.well_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drilling_observations_id'), 'drilling_observations', ['id'], unique=False)
    op.create_table('model_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('well_id', sa.String(), nullable=True),
    sa.Column('prediction_type', sa.String(), nullable=True),
    sa.Column('prediction_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('measured_depth', sa.Float(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['well_id'], ['wells.well_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_predictions_id'), 'model_predictions', ['id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('well_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('report_type', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('report_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extracted_text', sa.String(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['well_id'], ['wells.well_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_table('report_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_chunks_id'), 'report_chunks', ['id'], unique=False)
    # op.drop_table('spatial_ref_sys')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.drop_index(op.f('ix_report_chunks_id'), table_name='report_chunks')
    op.drop_table('report_chunks')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_model_predictions_id'), table_name='model_predictions')
    op.drop_table('model_predictions')
    op.drop_index(op.f('ix_drilling_observations_id'), table_name='drilling_observations')
    op.drop_table('drilling_observations')
    op.drop_index(op.f('ix_drilling_events_id'), table_name='drilling_events')
    op.drop_table('drilling_events')
    op.drop_index(op.f('ix_anomalies_id'), table_name='anomalies')
    op.drop_table('anomalies')
    op.drop_index(op.f('ix_wells_well_id'), table_name='wells')
    op.drop_index(op.f('ix_wells_id'), table_name='wells')
    op.drop_index('idx_wells_location', table_name='wells', postgresql_using='gist')
    op.drop_table('wells')
    op.drop_index(op.f('ix_formations_id'), table_name='formations')
    op.drop_index(op.f('ix_formations_formation_name'), table_name='formations')
    op.drop_table('formations')
    op.drop_index(op.f('ix_candidate_evaluations_id'), table_name='candidate_evaluations')
    op.drop_index(op.f('ix_candidate_evaluations_candidate_id'), table_name='candidate_evaluations')
    op.drop_index('idx_candidate_evaluations_location', table_name='candidate_evaluations', postgresql_using='gist')
    op.drop_table('candidate_evaluations')
    # ### end Alembic commands ###
